apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "postgresql"
  hostPath:
    path: "/Users/tony/Desktop/PersistentVolume/postgresql"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  storageClassName: "postgresql"
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
spec:
  selector:
    matchLabels:
      app: postgresql-app
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-app
    spec:
      containers:
      - name: postgresql-app
        image: postgres:latest
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: root_admin
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresql-volume
      volumes:
      - name: postgresql-volume
        persistentVolumeClaim:
          claimName: postgresql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: postgresql-cluster
spec:
  type: ClusterIP
  selector:
    app: postgresql-app
  ports:
  - port: 5432
    targetPort: 5432