apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
spec:
  selector:
    matchLabels:
      app: kibana-app
  template:
    metadata:
      labels:
        app: kibana-app
    spec:
      containers:
        - name: kibana-app
          image: kibana:7.16.3
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elastic-search-cluster:9200
            - name: SERVER_BASEPATH
              value: /kibana
          ports:
            - containerPort: 5601

---

apiVersion: v1
kind: Service
metadata:
  name: kibana-cluster
spec:
  type: ClusterIP
  selector:
    app: kibana-app
  ports:
  - port: 5601
    targetPort: 5601
    protocol: TCP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/kibana(/|$)(.*)"
        backend:
          service:
            name: kibana-cluster
            port: 
              number: 5601
