apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "rabbitmq"
  hostPath:
    path: "/Users/tony/Desktop/PersistentVolume/rabbitmq"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  storageClassName: "rabbitmq"
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  selector:
    matchLabels:
      app: rabbitmq-app
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-app
    spec:
      containers:
      - name: rabbitmq-app
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
          name: queue
        - containerPort: 15672
          name: ui
        volumeMounts:
          - mountPath: /var/lib/rabbitmq
            name: rabbitmq-volume
      volumes:
        - name: rabbitmq-volume
          persistentVolumeClaim:
            claimName: rabbitmq-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-cluster
spec:
  type: ClusterIP
  selector:
    app: rabbitmq-app
  ports:
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: ui-port
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: rabbitmq-port

---

# apiVersion: v1
# kind: Service
# metadata:
#   name: rabbitmq-loadbalancer
# spec:
#   type: LoadBalancer
#   selector:
#     app: rabbitmq-deployment
#   ports:
#   - port: 15672
#     targetPort: 15672
#     protocol: TCP
#     name: ui-port
#   - port: 5672
#     targetPort: 5672
#     protocol: TCP
#     name: rabbitmq-port

# ---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /rabbitmq(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: rabbitmq-cluster
            port:
              number: 15672

