apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-search-pv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "elastic-search"
  hostPath:
    path: "/Users/tony/Desktop/PersistentVolume/elastic-search"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-search-pvc
spec:
  storageClassName: "elastic-search"
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-search-deployment
spec:
  selector:
    matchLabels:
      app: elastic-search-app
  template:
    metadata:
      labels:
        app: elastic-search-app
    spec:
      containers:
      - name: elastic-search-app
        image: elasticsearch:7.16.3
        env:
          - name: discovery.type
            value: single-node
          - name: ES_JAVA_OPTS
            value: -Xms512m -Xmx512m
        ports:
        - containerPort: 9200
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: elastic-search-volume
      volumes:
        - name: elastic-search-volume
          persistentVolumeClaim:
            claimName: elastic-search-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: elastic-search-cluster
spec:
  type: ClusterIP
  selector:
    app: elastic-search-app
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP