apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql-deployment
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      containers:
        - name: mysql-deployment
          image: mysql/mysql-server:8.0
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume
      volumes:
        - name: mysql-volume

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster
spec:
  selector:
    app: mysql-deployment
  ports:
    - port: 3306
      targetPort: 3306
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-loadbalancer
# spec:
#   selector:
#     app: mysql-deployment
#   ports:
#     - port: 3306
#       targetPort: 3306

# Trouble Shooting

# Host 127.0.0.1 is not allowed to connect to this MySQL server
# kubectl exec -it <pod_name> -- /bin/bash
# mysql -u root -p
# CREATE USER 'user'@'%' IDENTIFIED BY 'password';
# GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' WITH GRANT OPTION;
# FLUSH PRIVILEGES;